### ISSUE TITLE
ModuleNotFoundError: No module named 'qr_code'

### ISSUE THREAD

**Issue by AkashNagtilak** [IamOmaR22/Online-News-Portal-with-Django#11]
ModuleNotFoundError: No module named 'qr_code'

I face this issue.pip install qr_code i already install but why this issue?

**Comment by IamOmaR22** [comment]
Please install qr_code by using this command

`pip install django_qr_code`

**Comment by AkashNagtilak** [comment]
Honestly bro You did good job... I really Like Your Project

**Comment by IamOmaR22** [comment]
Thanks, brother. Thanks for your honest opinion.
